### ISSUE TITLE
Reducing disk usage

### ISSUE THREAD

**Issue by DeaftJoe** [a-r-j-u-n-s/SoulsSave#1]
Hey, first of all, just wanted to say thanks for building this project out -- exactly the type of thing I'm looking for.

Disk usage per backup can be reduced by up to 90% if you implement the following:

1. Only create a backup of the XX0000.sl2 file. I don't have experience with Elden Ring save management, but for the DS series and Sekiro, I never had an issue with only backing up this file.
2. Zip the backups. My early-game Elden Ring save goes from 28mb to 2mb in size after compression.

If you have any reservations about only backing up the sl2 file, zipping is still going to drastically reduce space consumption for the backups.

**Comment by a-r-j-u-n-s** [comment]
Thanks for checking out the project! I experimented a bit with this idea and you're right that it is much more efficient. I'll be making changes based on your recommendation
